require:
  - rubocop-i18n
  - rubocop-performance
  - rubocop-rails
  - rubocop-thread_safety

RailsI18n:
  Enabled: true
GetText:
  Enabled: false

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Rails/ContentTag:
  Enabled: false
